-- Initial schema for SharePay.
--
-- Note: PRAGMA foreign_keys / journal_mode / synchronous / busy_timeout are
-- connection-level settings, not persisted schema state, so they are NOT set
-- here. They are configured per-connection via SqliteConnectOptions in
-- src/db/pool.rs (see spec §3.4).
--
-- Status lifecycle (spec §2.5, expanded beyond the DB component's original
-- 3-state draft here since one agent owns both the schema and the state
-- machine that drives it):
--   draft -> pending_ocr -> awaiting_photo_retry -> pending_ocr (loop)
--   pending_ocr -> pending_confirmation (sums matched)
--   pending_confirmation -> open (host confirms; QR/join link now valid)
--   open -> closed (host explicitly closes)
--   any pre-open state -> expired (abandoned / TTL elapsed)
--   closed -> [row hard-deleted after retention window]
-- "Pre-open" states are: draft, pending_ocr, awaiting_photo_retry,
-- pending_confirmation. Items are addable/editable throughout all pre-open
-- states and lock only once the bill is open or closed (spec §2.5's "Items
-- frozen once open" rule) — see the triggers below.

CREATE TABLE bills (
    id                  TEXT PRIMARY KEY,        -- 128-bit random token (QR/Session component)
    host_token_hash     TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'draft'
                        CHECK (status IN (
                            'draft',
                            'pending_ocr',
                            'awaiting_photo_retry',
                            'pending_confirmation',
                            'open',
                            'closed',
                            'expired'
                        )),
    receipt_total       INTEGER,                 -- cents; nullable until parsed/confirmed
    tax_tip_amount      INTEGER NOT NULL DEFAULT 0,
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    opened_at           TEXT,
    closed_at           TEXT
);

CREATE TABLE items (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    bill_id      TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    price        INTEGER NOT NULL CHECK (price >= 0),
    sort_order   INTEGER NOT NULL,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX idx_items_bill_id ON items(bill_id, sort_order);

-- participants.id is an unguessable 128-bit random token (spec §2.4), not a
-- DB-assigned sequential integer — it's used as a bearer-token-like cookie
-- value, and sequential integers would let one participant trivially
-- guess/forge another's identity. Generated by the QR/Session component
-- (src/bill/token.rs) and passed in, same style as bills.id.
CREATE TABLE participants (
    id                       TEXT PRIMARY KEY,
    bill_id                  TEXT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    display_name             TEXT NOT NULL CHECK (length(trim(display_name)) > 0),
    display_name_normalized  TEXT GENERATED ALWAYS AS (lower(trim(display_name))) STORED,
    joined_at                TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (bill_id, display_name_normalized)
);
CREATE INDEX idx_participants_bill_id ON participants(bill_id);

CREATE TABLE item_markers (
    item_id         INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    participant_id  TEXT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
    marked_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    PRIMARY KEY (item_id, participant_id)
);
CREATE INDEX idx_item_markers_participant ON item_markers(participant_id, item_id);

-- Defense-in-depth (spec §3.6): items are locked once the parent bill
-- reaches 'open' or 'closed'. They remain addable/editable through every
-- pre-open state (draft, pending_ocr, awaiting_photo_retry,
-- pending_confirmation) since that's when OCR parses items and the host
-- reviews/edits them (spec §2.5). The API layer (src/pricing/api.rs) is the
-- primary enforcement point (returns a typed BillAlreadyOpen error); these
-- triggers are a backstop against a future code path forgetting the check.
CREATE TRIGGER trg_items_locked_after_open_insert
BEFORE INSERT ON items
WHEN (SELECT status FROM bills WHERE id = NEW.bill_id) IN ('open', 'closed')
BEGIN
    SELECT RAISE(ABORT, 'items are locked once the bill is open');
END;

CREATE TRIGGER trg_items_locked_after_open_update
BEFORE UPDATE ON items
WHEN (SELECT status FROM bills WHERE id = OLD.bill_id) IN ('open', 'closed')
BEGIN
    SELECT RAISE(ABORT, 'items are locked once the bill is open');
END;

CREATE TRIGGER trg_items_locked_after_open_delete
BEFORE DELETE ON items
WHEN (SELECT status FROM bills WHERE id = OLD.bill_id) IN ('open', 'closed')
BEGIN
    SELECT RAISE(ABORT, 'items are locked once the bill is open');
END;
